### PR TITLE
Fix legacy match score rank value

### LINKED ISSUE #11591: osu api always show "F" rank from get_match
Code
Code_mo1cjrEchp
Result
WindowsTerminal_x77y3RhNZK
Match link: https://osu.ppy.sh/community/matches/115977090
Score: https://osu.ppy.sh/scores/3744935251

### PR DESCRIPTION
**Pull request by nanaya**
Resolves #11591.

This recalculates the value every time but I think it's already done for legacy score rank anyway, so 🤷

### CODE REVIEW

File: app/Models/Traits/Scoreable.php [hunk 1]
```diff
@@ -74,7 +74,7 @@ public function accuracy(): float
 
     public function recalculateRank(): void
     {
-        if (!$this->passed) {
+        if (!$this->pass) {
```
Comment (notbakaneko) [inline app/Models/Traits/Scoreable.php:77]: `Solo\Score` doesn't have a `pass`; actually, the function should probably be moved out of the trait since it's only used by legacy scores.

**Review by notbakaneko — CHANGES_REQUESTED** [review]

File: app/Models/Traits/Scoreable.php (hunk 1 above)
Comment (nanaya) [reply app/Models/Traits/Scoreable.php:77]: but Solo\Score doesn't use this trait? 🤔

Comment (notbakaneko) [reply app/Models/Traits/Scoreable.php:77]: does it not? 🤔

Comment (notbakaneko) [reply app/Models/Traits/Scoreable.php:77]: Oh wait, I mean because the naming in `Solo\Score::makeLegacyEntry` with the variable being `$score` and the method being named `recalculateRank` makes it confusing and the method is only used in legacy scores now.

I guess that can be a separate issue 🤷

**Review by notbakaneko — APPROVED** [review]
