### PR TITLE
Fix not being able to delete grouped notifications

### LINKED ISSUE #6900: Wrong parameter passed for batch notification destroy
Recent update broke deleting notifications by identity as the frontend for deleting is still sending identities in older format.

Sentry Issue: [OSU-WEB-7SX](https://sentry.io/organizations/ppy/issues/2043495116/?referrer=github_integration)

### PR DESCRIPTION
**Pull request by notbakaneko**
closes #6900

### CODE REVIEW

**Comment by nanaya** [comment]
May want to fix the backend error as well when invalid parameter is passed.

File: app/Libraries/Notification/BatchIdentities.php [hunk 1]
```diff
@@ -46,6 +44,15 @@ public static function fromParams(array $params)
         return $obj;
     }
 
+    public static function scrubIdentities(array $params)
+    {
+        $identities = array_map(function ($param) {
+            return is_array($param) ? static::scrubIdentity($param) : null;
+        }, $params);
+
+        return array_values(array_filter($identities));
```
Comment (nanaya) [inline app/Libraries/Notification/BatchIdentities.php:53]: maybe foreach and only add to array if not null instead of this map/filter/values chain?

**Review by nanaya — CHANGES_REQUESTED** [review]

**Review by nanaya — APPROVED** [review]
