### PR TITLE
Mark as read fixes for the web chat client

### LINKED ISSUE #4896: Opening a chat notification should dismiss all related notifications
A notification pops up for each message a user sends you. If the notification for one message is clicked, the rest remain active, which feels really bad.

### PR DESCRIPTION
**Pull request by nekodex**
Fixes:
 - when initially loading the chat page, a mark-as-read for the starting channel is not always sent
 - while actively looking at a channel, mark-as-read isn't always sent reliably

resolves #4896

### CODE REVIEW

File: resources/assets/lib/chat/chat-orchestrator.ts [hunk 1]
```diff
@@ -147,15 +152,23 @@ export default class ChatOrchestrator implements DispatchListener {
...
-    const lastRead = channel.lastMessageId;
+    const lastReadId = channel.lastMessageId;
 
     if (!channel.isUnread) {
       return;
     }
 
-    this.api.markAsRead(channel.channelId, lastRead)
+    // We don't need to send mark-as-read for our own messages, as the cursor is automatically bumped forward server-side when sending messages.
+    const lastSentMessage = channel.messages.find((message) => message.messageId === lastReadId);
```
Comment (nanaya) [inline resources/assets/lib/chat/chat-orchestrator.ts]: this probably should be from last index otherwise the loop will get longer over time?

File: resources/assets/lib/chat/chat-orchestrator.ts [hunk 2]
```diff
@@ -18,7 +18,7 @@
 
 import {
   ChatChannelPartAction,
-  ChatChannelSwitchAction,
+  ChatChannelSwitchAction, ChatMessageAddAction,
```
Comment (nanaya) [inline resources/assets/lib/chat/chat-orchestrator.ts]: the others are one line per thing
