### PR TITLE
Fix null artist_unicode and title_unicode fields

### LINKED ISSUE #7380: artist_unicode and title_unicode are null on old beatmaps
I did `JSON.parse(document.getElementById('json-beatmapset').textContent)` in browser's developer console, and I just noticed that the artist_unicode and title_unicode are null, while other (newer) beatmaps has the value (usually same value as non-unicode property)
Beatmap URL: https://osu.ppy.sh/beatmapsets/34348#osu/111680
I think it's just because it's an old map (submitted in 2011), but I think it shouldn't be null and should show the same value as a non-Unicode one instead (just like any other maps).

For reference: https://osu.ppy.sh/beatmapsets/1348446#osu/2792231
This map has non-null artist_unicode and title_unicode.

### PR DESCRIPTION
**Pull request by notbakaneko**
closes #7380

Automatically fallback to `artist` and `title`.

Wonder if they should be named something else 🤔 
(yes the function order is weird)

### CODE REVIEW

File: app/Models/Beatmapset.php [hunk 1]
```diff
@@ -1275,11 +1275,16 @@ private function getBBCode()
         return new BBCodeFromDB($description, $post->bbcode_uid, $options);
     }
 
+    public function getArtistUnicodeAttribute()
+    {
+        return $this->attributes['artist_unicode'] ?? $this->artist;
```
Comment (nanaya) [inline app/Models/Beatmapset.php:1280]: Also for the other one

```suggestion
    public function getArtistUnicodeAttribute($value)
    {
        return $value ?? $this->artist;
```

File: resources/assets/lib/beatmapsets/beatmapset-json.ts [hunk 2]
```diff
@@ -93,6 +93,6 @@ export interface BeatmapsetJson {
   nsfw: boolean;
   status: BeatmapsetStatus;
   title: string;
-  title_unicode: string | null;
+  title_unicode: string;
```
Comment (nanaya) [inline resources/assets/lib/beatmapsets/beatmapset-json.ts:96]: should update `artist_unicode` one as well?

**Review by nanaya — CHANGES_REQUESTED** [review]

File: resources/assets/lib/beatmapsets/beatmapset-json.ts (hunk 2 above)
Comment (notbakaneko) [reply resources/assets/lib/beatmapsets/beatmapset-json.ts:96]: huh, I thought I updated it 🤔

**Review by nanaya — APPROVED** [review]
