### PR TITLE
Fix front-end part of full BN nomination check

### LINKED ISSUE #6922: Probationary BN cannot nominate a map nominated by a full BN
Jerry (probationary taiko bn) apparently can't nominate https://osu.ppy.sh/beatmapsets/1121548/discussion, which is currently nominated by frukoyurdakul (full taiko bn). Probably related to the new nomination restrictions from https://github.com/ppy/osu-web/pull/6832.

### PR DESCRIPTION
**Pull request by nanaya**
Resolves #6922.

### CODE REVIEW

File: resources/assets/lib/beatmapsets/beatmapset-json.ts [hunk 1]
```diff
@@ -13,6 +13,17 @@ interface BeatmapsetCovers {
   slimcover: string;
 }
 
+export function isBeatmapsetNominationEvent(x: BeatmapsetEvent): x is BeatmapsetNominationEvent {
+  return x.type === 'nominate' && x.comment != null && Array.isArray(x.comment.modes);
```
Comment (nekodex) [inline resources/assets/lib/beatmapsets/beatmapset-json.ts:17]:
```suggestion
  return x.type === 'nominate' && Array.isArray(x.comment?.modes);
```

Comment (nanaya) [reply resources/assets/lib/beatmapsets/beatmapset-json.ts:17]: But that will call `isArray` on `undefined` :thinking:

Comment (nekodex) [reply resources/assets/lib/beatmapsets/beatmapset-json.ts:17]: which returns false anyway?

**Review by nekodex — APPROVED** [review]
