### PR TITLE
Fix notification not sent in some cases

### LINKED ISSUE #7325: Problem / DQ notifications rarely, if ever work on the website
I confirmed this with a significant number of people. They may have notifications enabled for their mode, or for every mode. In each case, many of them have not received any notifications for DQs or problems on qualified maps via the osu website in months.  Some receive notifications only sporadically.

For instance, I have all modes enabled for reports, and I have osu! enabled for disqualification notifications

image

Here is my notifications for beatmaps up to a few days ago:
image

Noted in green are report notifications.

But it's missing a LOT of things
By comparing to a #mapfeed history hosted by bots in discord servers and double checking the map discussion histories to be sure, there have been **24** disqualification events for osu! maps in the past 5 days, of which **0** showed up in my notifications. 
Similar goes for the problem notifications, only a few of many many more actually notified me. This is a serious issue as it means my reliable reporting tools are only available off platform, and the on-platform ones are broken.

For example https://osu.ppy.sh/beatmapsets/1228487/discussion/2822288/general#/2218546  https://osu.ppy.sh/beatmapsets/1395277/discussion/2880013/general#/2218508 these never notified me.

**Conclusion:**

Something is broken with them, and they aren't working as intended.

### PR DESCRIPTION
**Pull request by nanaya**
Mainly for "global" type notifications. Avoid doing large `whereIn` query.

Resolves #7325.

### CODE REVIEW

File: app/Jobs/Notifications/BroadcastNotificationBase.php [hunk 1]
```diff
@@ -80,39 +81,51 @@ private static function applyDeliverySettings(array $userIds)
...
+        $allBotUserIds = UserGroup
+            ::where('group_id', $botGroupId)
+            ->select('user_id');
+
+        // only consider users with bot as their primary group
         $botUserIds = User
-            ::whereIn('user_id', $userIds)
-            ->where('group_id', app('groups')->byIdentifier('bot')->getKey())
+            ::where('group_id', $botGroupId)
+            ->whereIn('user_id', $allBotUserIds)
```
Comment (notbakaneko) [inline app/Jobs/Notifications/BroadcastNotificationBase.php:128]: This part seems unnecessary - if going by the primary group, the `User::isBot` check is just `$this->group_id === app('groups')->byIdentifier('bot')->getKey();`
The old query was just limiting the result set to the list of users given instead of selecting all bot users.

I wonder if the list of bot users is something worth caching? 🤔

**Review by notbakaneko — CHANGES_REQUESTED** [review]

File: app/Jobs/Notifications/BroadcastNotificationBase.php (hunk 1 above)
Comment (nanaya) [reply app/Jobs/Notifications/BroadcastNotificationBase.php:128]: yeah there's no index on `group_id` on users table. The query should be simple enough (primary key lookup on two tables) and the amount of data is minimal so it should be fine doing this query (or at least not much worse compared to the current one) :shrug:

**Review by notbakaneko — APPROVED** [review]
