### PR TITLE
Fix landing chart alignment

### LINKED ISSUE #1593: Pippi's legs bleed through the online users graph in the home page.
this is very distracting
this is very very distracting

### PR DESCRIPTION
**Pull request by nanaya**
Ensure no blank space at the bottom.

Workarounds/fixes #1593 until someone comes up with better idea.

### CODE REVIEW

File: resources/assets/coffee/_classes/landing-user-stats.coffee [hunk 1]
```diff
@@ -41,7 +41,8 @@ class @LandingUserStats
 
     @svg = @svgContainerInner
       .append 'g'
-      .attr 'transform', "translate(#{@margin.left}, #{@margin.top})"
+      # Ensure no blank space at the bottom at certain zoom level in Firefox.
+      .attr 'transform', "translate(#{@margin.left}, #{@margin.top + 1})"
```
Comment (notbakaneko) [inline resources/assets/coffee/_classes/landing-user-stats.coffee]: is this one still needed?

Comment (nanaya) [reply resources/assets/coffee/_classes/landing-user-stats.coffee]: yes
