### PR TITLE
Fix `SelectOptions` ignoring `props.blackout`

### LINKED ISSUE #10443: Toggling report reason dropdown menu toggles screen dim
NaUjSfNgzv

### PR DESCRIPTION
**Pull request by Swekka**
Closes #10443

### CODE REVIEW

**Review by VEERT00X — APPROVED** [review]

**Review by VEERT00X — APPROVED** [review]
Yep This Should Do The Trick

File: resources/js/components/select-options.tsx [hunk 1]
```diff
@@ -47,12 +47,14 @@ export default class SelectOptions<T extends Option> extends React.Component<Pro
...
     makeObservable(this);
-    disposeOnUnmount(this, reaction(
-      () => this.showingSelector,
-      (showing) => {
-        blackoutToggle(showing, 0.5);
-      },
-    ));
+    if (props.blackout) {
+      disposeOnUnmount(this, reaction(
+        () => this.showingSelector,
```
Comment (nanaya) [inline resources/js/components/select-options.tsx:52]: while practically is fine as is currently, the props should be part of reaction value instead otherwise if when props changes at one point the blackout won't work properly.

**Review by nanaya — CHANGES_REQUESTED** [review]

File: resources/js/components/select-options.tsx [hunk 2]
```diff
@@ -50,7 +50,9 @@ export default class SelectOptions<T extends Option> extends React.Component<Pro
     disposeOnUnmount(this, reaction(
       () => this.showingSelector,
       (showing) => {
-        blackoutToggle(showing, 0.5);
+        if (props.blackout) {
```
Comment (nanaya) [inline resources/js/components/select-options.tsx:53]: reaction value is up there. also should use `this.props` instead

**Review by nanaya — CHANGES_REQUESTED** [review]

File: resources/js/components/select-options.tsx [hunk 3]
```diff
@@ -48,9 +48,11 @@ export default class SelectOptions<T extends Option> extends React.Component<Pro
     super(props);
     makeObservable(this);
     disposeOnUnmount(this, reaction(
-      () => this.showingSelector,
-      (showing) => {
-        blackoutToggle(showing, 0.5);
+      () => ({ blackout: this.props.blackout, showing: this.showingSelector }),
+      (value) => {
+        if (value.blackout) {
+          blackoutToggle(value.showing, 0.5);
```
Comment (nanaya) [inline resources/js/components/select-options.tsx:54]:
```suggestion
      () => this.props.blackout && this.showingSelector,
      (value) => {
        blackoutToggle(value ?? false, 0.5);
```

**Review by nanaya — CHANGES_REQUESTED** [review]

**Review by nanaya — APPROVED** [review]
