### PR TITLE
Fix very wide hype button

### LINKED ISSUE #9850: Hype button is too long with more than 50 hypes
It seems like now when your map has over 5 hypes, there's more bars below the hype count, for example like this :
osuwebissue20230210-6

But I discovered with one of my map (1606 hypes), the hype count went out of the screen (the button is 8025 px wide wtf!)

osuwebissue20230210-1600

_It's not the first time that [my map breaks the website](https://github.com/ppy/osu-web/issues/6285) lol_

This bug occurs either you're logged in or not. By looking across all maps, this bug starts to appears with 50 hypes or more. First, each bar is 0 or 1 px wide, but it seems that the padding between the bars remains the same, which should explain the bug. The more there are bars, the more the poor hype button is stretched, and in more extreme case, the hype count isn't even visible.
osuwebissue20230210-50

My screen is 1920x1080 btw

### PR DESCRIPTION
**Pull request by notbakaneko**
Fixes #9850

(when you expect clamp to be between 2 numbers, but it's not 👀 )

### CODE REVIEW

File: resources/js/components/discrete-bar.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ interface Props {
 
 export default function DiscreteBar(props: Props) {
   const current = Math.max(0, props.current);
-  const total = Math.max(1, clamp(props.total, current, props.total));
+  const total = Math.max(1, clamp(props.total, Math.min(current, props.total), props.total));
```
Comment (nanaya) [inline resources/js/components/discrete-bar.tsx:17]: I have a feeling it was just me at one point thought the bars should be at least as many as current count. Otherwise might as well just
```suggestion
  const total = Math.max(1, props.total);
```

**Review by nanaya — CHANGES_REQUESTED** [review]

File: resources/js/components/discrete-bar.tsx (hunk 1 above)
Comment (notbakaneko) [reply resources/js/components/discrete-bar.tsx:17]: not sure how well hundreds of bars in a small space would render well 🤔

**Review by nanaya — APPROVED** [review]
