### PR TITLE
Beatmap scoreboard revamp

### LINKED ISSUE #509: Scores are not aligned properly with some names on mobile
misscores

Giving attention to ranks 36, 37, 40, 46, 49

### LINKED ISSUE #1998: Ruleset-specific counters are missing from beatmap pages
We should be able to see ruleset-specific counts where necessary as per old rankings.

osu!catch -> droplets
osu!taiko -> large hits
osu!mania -> 500/MAX

### LINKED ISSUE #2005: [Mobile] Scoreboards on the beatmapset pages are totally broken

### PR DESCRIPTION
**Pull request by nekodex**
A light/daytime remix of the scoreboard in @arflyte's WIP redesign for the beatmapset page.

closes #1998, closes #509, closes #2005

### CODE REVIEW

**Comment by nekodex** [comment]
note to self: make pure component

File: app/Transformers/BeatmapTransformer.php [hunk 1]
```diff
@@ -30,6 +30,7 @@ class BeatmapTransformer extends Fractal\TransformerAbstract
         'scoresBest',
         'failtimes',
         'beatmapset',
+        'maxCombo',
```
Comment (nanaya) [inline app/Transformers/BeatmapTransformer.php]: now we use snake because I said so 🐍

File: resources/assets/less/bem-index.less [hunk 2]
```diff
@@ -52,9 +52,9 @@
 @import "bem/beatmap-pack-download";
 @import "bem/beatmap-pack-items";
 @import "bem/beatmap-packs";
-@import "bem/beatmap-score-big";
 @import "bem/beatmap-score-top";
 @import "bem/beatmap-scoreboard-top";
+@import "bem/beatmap-scoreboard-table";
```
Comment (nanaya) [inline resources/assets/less/bem-index.less]: doesn't seem sorted right =D

File: resources/assets/less/bem/beatmap-score-top.less [hunk 3]
```diff
@@ -88,58 +77,78 @@
...
+    flex-shrink: 1;
 
-  &__stats-top {
-    display: flex;
+    @media @desktop {
+      margin: 5px 10px 5px 0px;
+      justify-content: flex-end;
+    }
+
+    @media @mobile {
```
Comment (nanaya) [inline resources/assets/less/bem/beatmap-score-top.less]: not needed because there's override in `@media @desktop`?

File: resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+          for stat in props.hitTypeMapping
+            th key: stat[0], className: "#{bn}__header #{bn}__header--hitstat", stat[0]
+          th className: "#{bn}__header #{bn}__header--miss", 'miss'
+          th className: "#{bn}__header #{bn}__header--pp", 'pp'
+          th className: "#{bn}__header #{bn}__header--mods", 'mods'
+
+      tbody className: "#{bn}__body",
+        for score, i in props.scores
+          tr
+            className: "#{bn}__body-row#{(if i == 0 then " #{bn}__row--first" else '')}"
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee]: `__body-row--first`?

File: resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+                  country: props.countries[score.user.country_code]
+                  classModifiers: ['scoreboard', 'small-box']
+            td {},
+              a
+                className: "#{bn}__user-link"
+                href: laroute.route 'users.show', user: score.user.id
+                score.user.username
+
+            td className: (if score.max_combo == props.beatmap.maxCombo?[0] then "#{bn}__perfect" else ''),
+              "#{score.max_combo.toLocaleString()}x"
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee]: &times;? :D (`&times;`)

File: resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+
+            for stat in props.hitTypeMapping
+              td
+                key: stat[0]
+                className: (if score.statistics["count_#{stat[1]}"] == 0 then "#{bn}__zero" else ''),
+                score.statistics["count_#{stat[1]}"].toLocaleString()
+
+            td className: (if score.statistics.count_miss == 0 then "#{bn}__zero" else ''),
+              score.statistics.count_miss
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee]: `toLocaleString()`?

File: resources/assets/coffee/react/beatmapset-page/score-top.coffee [hunk 7]
```diff
@@ -25,68 +25,69 @@ BeatmapsetPage.ScoreTop = (props) ->
...
+              key: stat[0]
+              className: "#{bn}__stat"
+              div className: "#{bn}__stat-header",
+                stat[0]
+              div className: "#{bn}__stat-value #{bn}__stat-value--score #{bn}__stat-value--smaller",
+                props.score.statistics["count_#{stat[1]}"].toLocaleString()
 
-          div className: "#{bn}__stat hidden-xs",
+        div className: "#{bn}__stats",
+          div className: "#{bn}__stat",
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmapset-page/score-top.coffee]: misses probably better grouped together with other hits counts? (or why are they even grouped)



Doesn't seem to be properly aligned (300/100/50 columns group).

File: resources/assets/coffee/react/beatmapset-page/score-top.coffee [hunk 8]
```diff
@@ -25,68 +25,69 @@ BeatmapsetPage.ScoreTop = (props) ->
...
             div className: "#{bn}__stat-header",
               osu.trans 'beatmapsets.show.scoreboard.stats.misses'
-            div className: "#{bn}__stat-value #{bn}__stat-value--score",
+            div className: "#{bn}__stat-value #{bn}__stat-value--score #{bn}__stat-value--smaller",
               props.score.statistics.count_miss
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmapset-page/score-top.coffee]: might as well add the `toLocaleString()`

File: resources/assets/coffee/react/beatmapset-page/score-top.coffee (hunk 7 above)
Comment (nekodex) [reply resources/assets/coffee/react/beatmapset-page/score-top.coffee]: so they wrap in those groups on mobile and look less silly

File: resources/assets/coffee/react/beatmapset-page/score-top.coffee (hunk 8 above)
Comment (nekodex) [reply resources/assets/coffee/react/beatmapset-page/score-top.coffee]: oh yeah sure for those top ranking scores that have 1000+ misses 🙄

Comment (nanaya) [reply resources/assets/coffee/react/beatmapset-page/score-top.coffee]: and you'll always be in top ranking, right?

Comment (nekodex) [reply resources/assets/coffee/react/beatmapset-page/score-top.coffee]: somehow I doubt there are any maps that exist where you can pass with 1000+ misses?...

File: resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee (hunk 5 above)
Comment (nekodex) [reply resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee]: uh, Exo 2 doesn't seem to have that... ? O_o

File: resources/assets/coffee/react/beatmapset-page/score-top.coffee (hunk 8 above)
Comment (nanaya) [reply resources/assets/coffee/react/beatmapset-page/score-top.coffee]: nf mania?

File: resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee (hunk 5 above)
Comment (nanaya) [reply resources/assets/coffee/react/beatmapset-page/scoreboard-table.coffee]: right, now I remember something like that for popup close button as well ヽ( ﾟ ヮﾟ)ﾉ

File: resources/assets/coffee/react/beatmapset-page/scoreboard.coffee [hunk 9]
```diff
@@ -24,6 +24,18 @@ class BeatmapsetPage.Scoreboard extends React.Component
   MANIA_KEY_MODS = ['4K', '5K', '6K', '7K', '8K', '9K']
   MANIA_MODS = ['NM', 'EZ', 'NF', 'HT', 'HR', 'SD', 'PF', 'DT', 'NC', 'FI', 'HD', 'FL']
 
+  hitTypeMapping: =>
```
[the remark this answers is not in the document]
Comment (nekodex) [reply resources/assets/coffee/react/beatmapset-page/scoreboard.coffee]: eeh that can be done in another pull request imo
