### PR TITLE
Fix first time donation messages

### LINKED ISSUE #3862: Recent activity's first osu!supporter purchase not showing correctly
Recently bought osu!supporter for the first time, and it doesn't show the string linked below.

https://github.com/ppy/osu-web/blob/master/resources/lang/en/events.php#L33

Profile: https://osu.ppy.sh/users/8549835

### PR DESCRIPTION
**Pull request by notbakaneko**
closes #3862

---

### CODE REVIEW

File: app/Libraries/Fulfillments/SupporterTagFulfillment.php [hunk 1]
```diff
@@ -40,6 +41,7 @@ public function run()
     {
         $this->throwOnFail($this->validateRun());
 
+        $this->continued = $this->order->user->supporterTagPurchases->count() > 0;
```
Comment (nanaya) [inline app/Libraries/Fulfillments/SupporterTagFulfillment.php]: Probably faster with `...Purchases()->exists()`?
