### PR TITLE
Fix bad English in the Store localization file

### LINKED ISSUE #1932: Bad english on store out-of-stock message
`This type is currently out of stock :(. Try other type or check back soon.`

should probably read something like

`Unfortunately this item is out of stock. Use the dropdown to choose a different type or check back later!`

### PR DESCRIPTION
**Pull request by TPGPL**
Closes #1932

### CODE REVIEW

File: resources/lang/en/store.php [hunk 1]
```diff
@@ -47,8 +47,8 @@
         'name' => 'Name',
 
         'stock' => [
-            'out' => 'Currently out of stock :(. Check back soon.',
-            'out_with_alternative' => 'This type is currently out of stock :(. Try other type or check back soon.',
+            'out' => 'This item is currently out of stock. Check back later!',
+            'out_with_alternative' => 'Unfortunately this item is out of stock. Use the dropdown to choose a different type or check back later!',
```
Comment (Aergwyn) [inline resources/lang/en/store.php]: `choose a different type`? This still reads sketchy. (May be my ignorance because of missing knowledge of the specifics of the page though)

Comment (TPGPL) [reply resources/lang/en/store.php]: probably different type of merchandise

**Comment by peppy** [comment]
Please stop removing other languages when fixing english.
