### PR TITLE
Remove filtering multiplayer rooms by route path parameter

### LINKED ISSUE #10491: Filtering multiplayer Rooms by path mode parameter does not work
e.g. `rooms?mode=owned` works fine but `rooms/owned` doesn't do anything (since #6278 it seems)

Probably better to remove it instead or re-adding it back in, since it hasn't worked for a long time and no one has made an issue about it; also doesn't make as much sense anymore as a route as `rooms/latest` exists and returns a single room

### PR DESCRIPTION
**Pull request by notbakaneko**
closes #10491

Added some basic docs for `@queryParam` so I don't have to keep digging for it; `category` is omitted due to being deprecated.

### CODE REVIEW

File: app/Http/Controllers/Multiplayer/RoomsController.php [hunk 1]
```diff
@@ -18,6 +18,19 @@ public function __construct()
         $this->middleware('require-scopes:public', ['only' => ['index', 'leaderboard', 'show']]);
     }
 
+    /**
+     * Get Multiplayer Rooms
```
Comment (nanaya) [inline app/Http/Controllers/Multiplayer/RoomsController.php:22]: need a `@category` specifier otherwise this goes to "Undocumented" 🤔

File: app/Http/Controllers/Multiplayer/RoomsController.php [hunk 2]
```diff
@@ -18,6 +18,19 @@ public function __construct()
...
+     *
+     * Returns a list of multiplayer rooms.
+     *
+     * ---
+     *
+     * @queryParam limit Maximum number of results. No-example
+     * @queryParam mode Filter mode; `all`, `ended`, `participated`, `owned`. Defaults to active rooms only if not sepcified. No-example
```
Comment (nanaya) [inline app/Http/Controllers/Multiplayer/RoomsController.php:29]: can just pretend `active` param for the default (and maybe add that as part of the switch)

**Review by nanaya — CHANGES_REQUESTED** [review]

File: app/Http/Controllers/Multiplayer/RoomsController.php (hunk 2 above)
Comment (notbakaneko) [reply app/Http/Controllers/Multiplayer/RoomsController.php:29]: wait, that's why it was `default` in the first place 🙈

File: app/Http/Controllers/Multiplayer/RoomsController.php [hunk 3]
```diff
@@ -18,6 +18,21 @@ public function __construct()
         $this->middleware('require-scopes:public', ['only' => ['index', 'leaderboard', 'show']]);
     }
 
+    /**
+     * Get Multiplayer Rooms
+     *
+     * Returns a list of multiplayer rooms.
+     *
+     * ---
```
Comment (nanaya) [inline app/Http/Controllers/Multiplayer/RoomsController.php:26]: should only be here if there's response half of the docs otherwise this just adds a random line

**Review by nanaya — APPROVED** [review]
