### PR TITLE
Move Beatmapset SearchResponse interface to own file

### LINKED ISSUE #12169: Displayed default sort order is incorrect when searching beatmaps using query string options
Due to additional querystring parsing server-side that's not client side, the displayed default sort order is not correct (result order is still correct), i.e. shows `Relevance` when it's actually `Ranked`.

### PR DESCRIPTION
**Pull request by notbakaneko**
Separated from trying to fix #12169 since it turned out to be less simple that I thought....

### CODE REVIEW

File: resources/js/interfaces/beatmapset-search-response.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the GNU Affero General Public License v3.0.
+// See the LICENCE file in the repository root for full licence text.
+
+import BeatmapsetExtendedJson from 'interfaces/beatmapset-extended-json';
+
+type SortField = 'artist' | 'difficulty' | 'favourites' | 'plays' | 'ranked' | 'rating' | 'relevance' | 'title';
```
Comment (nanaya) [inline resources/js/interfaces/beatmapset-search-response.ts:6]: combine with `sortNames` in https://github.com/ppy/osu-web/blob/ae31a218b68fbb2657de45999227348979553bad/resources/js/beatmaps/search-sort.tsx#L14 ?

**Review by nanaya — CHANGES_REQUESTED** [review]

**Review by nanaya — APPROVED** [review]
