### PR TITLE
Fix counting per-mode open issues

### LINKED ISSUE #2671: Issues on deleted difficulties should not count towards the total number of issues
https://osu.ppy.sh/beatmapsets/737418/discussion
All issues have been resolved, but the counter at the top of the page is showing 9 issues from the deleted difficulty, which can't be resolved.
The 9 issues still show up when switching to a different difficulty

screen shot 2018-03-11 at 4 10 47 pm

### PR DESCRIPTION
**Pull request by nanaya**
Fixes #2671.

### CODE REVIEW

File: resources/assets/coffee/react/beatmap-discussions/main.coffee [hunk 1]
```diff
@@ -205,16 +205,19 @@ class BeatmapDiscussions.Main extends React.PureComponent
       continue if _.isEmpty(d)
 
       if !d.deleted_at? && d.can_be_resolved && !d.resolved
-        if !d.beatmap_id? || !@beatmaps()[d.beatmap_id]?.deleted_at?
+        beatmap = @beatmaps()[d.beatmap_id]
+
+        if !d.beatmap_id? || (beatmap? && !beatmap.deleted_at?)
```
Comment (notbakaneko) [inline resources/assets/coffee/react/beatmap-discussions/main.coffee]: what's `!d.beatmap_id?` for?

Comment (nanaya) [reply resources/assets/coffee/react/beatmap-discussions/main.coffee]: discussion on general all.
