### PR TITLE
Delete scores on qualification

### LINKED ISSUE #2787: Qualifying should always remove leaderboards
previously disqualified maps do not delete the leaderboards upon requalification.

[this map is an example](https://osu.ppy.sh/beatmapsets/702111#osu/1544643): the top score on it was set before this one qualified 

it nukes upon hitting ranked anyways but it can cause a ton of broken replays in case stuff is remapped and constellations where the top play of a newly qualified map is months old and doesnt make any sense potentially

### PR DESCRIPTION
**Pull request by nanaya**
Fixes #2787.

### CODE REVIEW

File: app/Jobs/RemoveBeatmapsetBestScores.php [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+     * @return void
+     */
+    public function handle()
+    {
+        $beatmapIds = model_pluck($this->beatmapset->beatmaps(), 'beatmap_id');
+
+        foreach (Beatmap::MODES as $mode => $_modeInt) {
+            static::scoreClass($mode)::whereIn('beatmap_id', $beatmapIds)
+                ->orderBy('score_id')
+                ->where('score_id', '<', $this->maxScoreIds[$mode])
```
Comment (nekodex) [inline app/Jobs/RemoveBeatmapsetBestScores.php]: Shouldn't this be `<=`?
