### PR TITLE
Fix typo and wrong index data for converted mania maps

### LINKED ISSUE #7846: Approved beatmap shows wrong key count for mania convert
https://osu.ppy.sh/beatmapsets/4651#mania/24733
Beatmap shows as 5 key on the website:
image
But is actually a 6 key map:
image

### PR DESCRIPTION
**Pull request by nanaya**
Resolves #7846.

A full reindex is needed for correct search result.

### CODE REVIEW

File: app/Models/Beatmap.php [hunk 1]
```diff
@@ -158,7 +158,7 @@ public function getDiffSizeAttribute($value)
          * Matches client implementation.
          * all round()s here use PHP_ROUND_HALF_EVEN to match C# default Math.Round.
          * References:
-         * - (implmentation) https://github.com/ppy/osu/blob/c9276ce2b8b2eb728b1e5fc74f5f7ef81b0c6e09/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L36
+         * - (implmentation) https://github.com/ppy/osu/blob/6bbc23c831cd73bf126b31edb0bb4fa729f947d1/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L40
```
Comment (peppy) [inline app/Models/Beatmap.php:161]:
```suggestion
         * - (implementation) https://github.com/ppy/osu/blob/6bbc23c831cd73bf126b31edb0bb4fa729f947d1/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L40
```

**Review by peppy — CHANGES_REQUESTED** [review]

**Review by smoogipoo — APPROVED** [review]
Looks correct. Yeah I thought this was a thing that was implemented at one point, couldn't find the code in a quick search.

**Review by notbakaneko — APPROVED** [review]
