### PR TITLE
Show chat muted notice on existing channels

### LINKED ISSUE #5954: No note when replying to user blocking messages from non-friends
If a user is blocking messages from people not on their friends list (or has you blocked?) and messages you first, the note that normally appears under their name explaining why you can't message them does not appear. So when you go to reply, all of your messages fail/403 with no explanation and you are left wondering why that is the case. For example:
  

Typically you would see something like this:

### PR DESCRIPTION
**Pull request by nanaya**
Resolves #5954.

I sure hope the `moderated` column in Channel is properly set.

### CODE REVIEW

**Comment by nekodex** [comment]
Uh, unless I'm mistaken... pretty sure nothing actually sets that moderated flag yet 😒

(IIRC it was only half-implemented as an emergency switch or something)

**Comment by nanaya** [comment]
Well it doesn't matter if it's all false as the correct value for pm (which is the relevant part to this pr) is filled in differently 💯

File: app/Models/Chat/UserChannel.php [hunk 1]
```diff
@@ -147,6 +152,7 @@ function ($userChannel) use ($byChannelId, $byUserId, $channelMessageIds, $userI
                     $userActual = $targetUser->userScoped;
                     $presence['icon'] = $userActual->user_avatar;
                     $presence['name'] = $userActual->username;
+                    $presence['moderated'] = !priv_check_user($user, 'ChatStart', $userActual)->can();
```
Comment (notbakaneko) [inline app/Models/Chat/UserChannel.php:155]: should probably match this with sending messages which uses `ChatChannelSend`

Comment (nanaya) [reply app/Models/Chat/UserChannel.php:155]: I think last I checked it is way more query heavy compared to this one

Comment (notbakaneko) [reply app/Models/Chat/UserChannel.php:156]: it should probably include the `moderated` state still since that's part of the check when sending even if it's a pm channel

**Comment by TPGPL** [comment]
Resolves #3913 as well?
