### PR TITLE
Display nominations in order of nomination

### LINKED ISSUE #2084: Nominators are listed in wrong order
a
^Order in which the map was nominated according to history

b
v2 discussion page shows them in the opposite order which doesn't seem intended, listing the first nominator first would be a better approach, as already mentioned in discord.

This happens for all maps that get nominated in v2.

### PR DESCRIPTION
**Pull request by nekodex**
fixes #2084

### CODE REVIEW

File: resources/assets/coffee/react/beatmap-discussions/nominations.coffee [hunk 1]
```diff
@@ -233,7 +233,7 @@ class BeatmapDiscussions.Nominations extends React.PureComponent
                 className: "#{bn}__note #{bn}__note--nominators"
                 dangerouslySetInnerHTML:
                   __html: osu.trans 'beatmaps.nominations.nominated_by',
-                    users: nominators.map (user) ->
+                    users: nominators.reverse().map (user) ->
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmap-discussions/nominations.coffee]: I wonder if it's better to unshift instead of push when generating the array. A bit clearer about the order or something.

**Comment by nanaya** [comment]
also more like "display nominators"?
