### PR TITLE
font-awesome icon fixes

### LINKED ISSUE #2993: Reply and Resolve button is the wrong size
screen shot 2018-04-13 at 10 23 24 am

after clicking reply
screen shot 2018-04-13 at 10 23 45 am

### PR DESCRIPTION
**Pull request by nekodex**
Fixes missing icons in beatmap discussion and replaces cloud download icon.

cloud

fixes #2993

### CODE REVIEW

File: app/Http/Controllers/HomeController.php [hunk 1]
```diff
@@ -236,7 +236,7 @@ public function supportTheGame()
                 'perks' => [
                     // localization's name => icon
                     'osu_direct' => 'fas fa-search',
-                    'auto_downloads' => 'fas fa-cloud-download-alt',
+                    'auto_downloads' => 'fas fa-download',
                     'upload_more' => 'fas fa-cloud-upload-alt',
```
Comment (Joehuu) [inline app/Http/Controllers/HomeController.php]: regular upload icon too

Comment (nekodex) [reply app/Http/Controllers/HomeController.php]: That page is being replaced "soon" anyway.
