### PR TITLE
Fix popup menu clipping offscreen

### LINKED ISSUE #8029: Report beatmap & user button messed up on mobile
just noticed it's out of mobile layer portrait

browser: chrome latest version
os: android 10

### PR DESCRIPTION
**Pull request by notbakaneko**
closes #8029

### CODE REVIEW

File: resources/assets/lib/profile-page/extra-menu.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  return (
+    <div
+      className='btn-circle btn-circle--page-toggle btn-circle--page-toggle-detail'
+      title={osu.trans('common.buttons.show_more_options')}
+    >
+      <PopupMenu>
+        {() => (
+          <div className='simple-menu'>
+            <BlockButton
+              key='block'
```
Comment (nanaya) [inline resources/assets/lib/profile-page/extra-menu.tsx:24]: key not needed

File: resources/assets/coffee/react/profile-page/detail-bar.coffee [hunk 2]
```diff
@@ -93,38 +86,11 @@ export class DetailBar extends React.Component
...
-        className: 'simple-menu__item'
-        icon: true
-        key: 'report'
-        reportableId: @props.user.id
-        reportableType: 'user'
-        user: @props.user
-      items.push reportButton
-
-    return null if items.length == 0
+    return null unless core.currentUser? && core.currentUser.id != @props.user.id
```
Comment (nanaya) [inline resources/assets/coffee/react/profile-page/detail-bar.coffee:89]: looks like this should be using a static/standalone function in `ExtraMenu`

**Review by nanaya — CHANGES_REQUESTED** [review]

**Review by nanaya — APPROVED** [review]
