### PR TITLE
Fix line breaking in mobile nothing found page

### LINKED ISSUE #2078: Mobile - Wrong break line in beatmapsets search page
screenshot_20171222-223951
"nothing found" should follow "nope, " like this: (if break line)
```
[img]
[img].....nope, 
[img]nothing found.
[img]
```

rather than current: 
```
[img].....nope, 
nothing found.
```

¯\\\_(ツ)\_/¯

### PR DESCRIPTION
**Pull request by MegaApplePi**
fixes #2078

### CODE REVIEW

File: resources/assets/coffee/react/beatmaps/main.coffee [hunk 1]
```diff
@@ -91,7 +91,8 @@ class Beatmaps.Main extends React.PureComponent
                   src: '/images/layout/beatmaps/not-found.png'
                   alt: osu.trans("beatmaps.listing.search.not-found")
                   title: osu.trans("beatmaps.listing.search.not-found")
-                osu.trans("beatmaps.listing.search.not-found-quote")
+                div className: 'beatmapsets__empty--message',
```
Comment (nanaya) [inline resources/assets/coffee/react/beatmaps/main.coffee]: not needed (see below)

File: resources/assets/less/bem/beatmapsets.less [hunk 2]
```diff
@@ -30,9 +30,14 @@
...
 
   &__empty {
-    text-align: center;
+    display: flex;
+    justify-content: center;
     width: 100%;
     margin: 10px 0 -20px;
+
+    &--message{
+      align-self: center;
```
Comment (nanaya) [inline resources/assets/less/bem/beatmapsets.less]: add `align-items: center` in the element instead.
