### PR TITLE
Fix forum topic cover handling

### LINKED ISSUE #11226: Topic covers not viewable or editable
I briefly looked into this and it seems like somewhere around #10703 or #10655 is where this all stopped working. not 100% sure though

if it's as bad as it sounds (entirely broken for 6 months) and nobody reported it, I feel like that says something about how low the demand is for this feature... so maybe relevant as a future design consideration or something.

### PR DESCRIPTION
**Pull request by nanaya**
Resolves #11226.

- incorrect cover file check
- missing topic id on relevant model

### CODE REVIEW

**Comment by cl8n** [comment]
can still reproduce part of the issue by:
- make a new post
- upload a topic cover (using the edit cover button)
- refresh page

File: app/Http/Controllers/Forum/TopicsController.php [hunk 1]
```diff
@@ -431,7 +431,8 @@ public function show($id)
         $topic->incrementViewCount($currentUser, \Request::ip());
         $posts->last()->markRead($currentUser);
 
-        $coverModel = $topic->cover ?? new TopicCover();
+        // initiate new cover model separately to prevent it from getting used by opengraph
```
Comment (cl8n) [inline app/Http/Controllers/Forum/TopicsController.php:434]:
```suggestion
        // Instantiate new cover model separately to prevent it from getting used by opengraph
```
:thinking:

**Review by cl8n — APPROVED** [review]

**Review by notbakaneko — APPROVED** [review]
