### PR TITLE
Fix user lookups for numeric usernames

### LINKED ISSUE #1605: The /users/ route behave differently from the /u/ route
Found by @lslqtz 
https://osu.ppy.sh/u/2420195176 returns the profile of user whose username is 2420195176 .
https://osu.ppy.sh/users/2420195176 returns 404 .
Is this expected behavior? Or is this a bug?

### PR DESCRIPTION
**Pull request by cl8n**
closes #1605 
fixes 404s when looking up numeric usernames (ex. "630" - [old site](https://osu.ppy.sh/u/630), [new site](https://osu.ppy.sh/users/630))

not sure if this is the best way to go about it

### CODE REVIEW

File: app/Models/User.php [hunk 1]
```diff
@@ -363,10 +363,12 @@ public static function lookup($username_or_id, $lookup_type = null, $find_all =
...
                 if (is_numeric($username_or_id)) {
-                    $user = self::where('user_id', $username_or_id);
-                } else {
-                    $user = self::where('username', $username_or_id)->orWhere('username_clean', '=', $username_or_id);
+                    $user = self::lookup($username_or_id, 'id', $find_all);
+                    if ($user !== null) {
+                        return $user;
+                    }
                 }
+                $user = self::where('username', $username_or_id)->orWhere('username_clean', '=', $username_or_id);
```
Comment (nanaya) [inline app/Models/User.php]:
```
default:
  if (is_numeric) {
    $user = ...;
  }
  return $user ?? static::lookup(...);
```

Comment (cl8n) [reply app/Models/User.php]: aha I knew there had to be a better way. thanks
