### PR TITLE
Accept int for mods parameter

### LINKED ISSUE #8807: Beatmap attributes endpoint doesn't work with bitset number.
I get HTTP 422 {"error":"invalid mods specified"}, it does work if you wrap number in quotes making it a json string.

### PR DESCRIPTION
**Pull request by nanaya**
Fixes #8807.

### CODE REVIEW

File: app/Http/Controllers/BeatmapsController.php [hunk 1]
```diff
@@ -87,7 +87,7 @@ public function attributes($id)
         }
 
         if (isset($params['mods'])) {
-            if (ctype_digit($params['mods'])) {
+            if (is_numeric($params['mods'])) {
```
Comment (notbakaneko) [inline app/Http/Controllers/BeatmapsController.php:90]: `1.1` is numeric too (but then gets truncated by the cast) 🤔

Comment (nanaya) [reply app/Http/Controllers/BeatmapsController.php:90]: weird people deserve weird response. I don't think the function throws error for extraneous bits either so negatives and invalid bits are still accepted regardless

**Review by notbakaneko — APPROVED** [review]
