### PR TITLE
Fix online friends count

### LINKED ISSUE #1366: Online friends or Friends?
image
the "Online friends" should be "Friends" ?

but, iirc, Online friends display ***online firends count***, not ***friends count*** in the past.

### PR DESCRIPTION
**Pull request by nekodex**
fixes #1366

### CODE REVIEW

File: app/Models/User.php [hunk 1]
```diff
@@ -998,7 +998,7 @@ public function scopeDefault($query)
 
     public function scopeOnline($query)
     {
-        return $query->where('user_lastvisit', '>', Carbon::now()->subMinutes(config('osu.user.online_window')));
+        return $query->whereRaw('user_lastvisit > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL '.config('osu.user.online_window').' MINUTE))');
```
Comment (nanaya) [inline app/Models/User.php]: or `Carbon::...->format(static::getDateFormat())` 💃
