### PR TITLE
Fix incorrect check for completed playlist item

### LINKED ISSUE #10778: Lazer Non-osu! standard scores are not recorded in Multiplayer lobbies
Looks like scores from other modes are not recorded or represented in the frontend when viewing a multiplayer lobby when done on Lazer.

image

### PR DESCRIPTION
**Pull request by nanaya**
The change to always create playlist item high score entry broke the exist check.

Note: untested.

Resolves #10778 (probably)

### CODE REVIEW

**Review by peppy — APPROVED** [review]

File: app/Models/Multiplayer/UserScoreAggregate.php [hunk 1]
```diff
@@ -202,7 +202,7 @@ public function userRank()
 
     private function updateUserTotal(ScoreLink $currentScoreLink, PlaylistItemUserHighScore $prev)
     {
-        if ($prev->exists) {
+        if ($prev->last_score_id !== null) {
```
Comment (notbakaneko) [inline app/Models/Multiplayer/UserScoreAggregate.php:205]: it's `score_id`....
