### PR TITLE
Fix comments listing page count

### LINKED ISSUE #5481: Last pages of the comments listing don't have any comments
It says that [15935](https://osu.ppy.sh/comments?page=15935) is the last page while it's actually [15042](https://osu.ppy.sh/comments?page=15042) (atm at least)

---
Video: https://streamable.com/k4f3l
Url: https://osu.ppy.sh/comments

### PR DESCRIPTION
**Pull request by notbakaneko**
- fix paginator count
- also fix query param not being included in paginator.

closes #5481

### CODE REVIEW

File: app/Http/Controllers/CommentsController.php [hunk 1]
```diff
@@ -116,17 +117,16 @@ public function index()
...
             $commentPagination = new LengthAwarePaginator(
                 [],
-                Comment::count(),
+                $commentBundle->countForPaginator(),
                 $commentBundle->params->limit,
                 $commentBundle->params->page,
                 [
                     'path' => LengthAwarePaginator::resolveCurrentPath(),
-                    'query' => $commentBundle->params->forUrl(),
+                    'query' => array_merge($commentBundle->params->forUrl(), ['commentable_id' => $id, 'commentable_type' => $type]),
```
Comment (nanaya) [inline app/Http/Controllers/CommentsController.php]: should those just be part of `forUrl`?

Comment (notbakaneko) [reply app/Http/Controllers/CommentsController.php]: it seemed odd to have it as part of `forUrl` when `CommentBundleParams` didn't do anything with them 🤷‍♂
